INSERT INTO article (name, type_id, unity_price, image) VALUES
('Home Deodorizer', 3, 3.49, 'home-deodorizer.png'),
('Toilet Brush', 3, 7.99, 'toilet-brush.png'),
('Laundry Stain Remover', 3, 6.49, 'laundry-stain-remover.png'),
('Furniture Polish', 3, 9.99, 'furniture-polish.png'),
('Carpet Cleaner', 3, 11.99, 'carpet-cleaner.png'),
('Jogging Pants', 4, 24.99, 'jogging-pants.png'),
('Dress Shirt', 4, 39.99, 'dress-shirt.png'),
('Skirt', 4, 29.99, 'skirt.png'),
('Hat', 4, 18.99, 'hat.png'),
('Watch', 4, 99.99, 'watch.png'),
('Leather Belt', 4, 29.99, 'leather-belt.png'),
('Wool Scarf', 4, 22.99, 'wool-scarf.png'),
('Laptop Bag', 4, 59.99, 'laptop-bag.png'),
('Decorative Pillow', 5, 19.99, 'decorative-pillow.png'),
('Photo Frame', 5, 12.99, 'photo-frame.png'),
('Table Lamp', 5, 29.99, 'ceramic-table-lamp.png'),
('Velvet Cushion', 5, 12.99, 'velvet-cushion.png'),
('Jute Woven Rug', 5, 39.99, 'jute-woven-rug.png'),
('Cotton Cushion Cover', 5, 8.99, 'cotton-cushion-cover.png'),
('Blown Glass Vase', 5, 19.99, 'blown-glass-vase.png'),
('Wool Blanket', 5, 49.99, 'wool-blanket.png'),
('Wooden Wall Clock', 5, 34.99, 'wooden-wall-clock.png'),
('Metal Wall Mirror', 5, 42.99, 'metal-wall-mirror.png'),
('Wooden Photo Frame', 5, 8.99, 'wooden-photo-frame.png'),
('Essential Oil', 6, 12.99, 'essential-oil.png'),
('Olive Oil Soap', 6, 6.99, 'olive-oil-soap.png'),
('Tea Infuser', 6, 4.99, 'stainless-steel-tea-infuser.png'),
('Electric Foot Massager', 6, 49.99, 'electric-foot-massager.png'),
('Heating Pad', 6, 29.99, 'heating-pad.png'),
('Uno Card Game', 7, 9.99, 'uno.png'),
('Monopoly', 29.99, 7, 'monopoly.png'),
('Jenga', 14.99, 7, 'jenga.png'),
('Lego', 24.99, 7, 'lego.png'),
('Beyblade', 12.99, 7, 'beyblade.png'),
('Trivial Pursuit Board Game', 39.99, 7, 'trivial-pursuit.png'),
('Modeling Compound', 6.99, 7, 'modelling-campound.png'),
('Catan Board Game', 49.99, 7, 'catan-board-game.png'),
('Doll', 29.99, 7, 'doll.png'),
('Body Lotion', 12.99, 8, 'body-lotion.png'),
('Self care cream', 39.99, 8, 'anti-aging-cream.png'),
('Foundation', 14.99, 8, 'foundation.png'),
('Eyebrow Pencil', 21.99, 8, 'eyebrow-pencil.png'),
('Perfume', 89.99, 8, 'perfume.png'),
('Swimsuit', 19.99, 'swimsuit.png'),
('Yoga Mat', 39.99, 10, 'yoga-mat.png'),
('Hiking Socks', 9.99, 9, 'hiking-socks.png'),
('Water Bottle', 12.50, 10, 'water-bottle.png'),
('Boxing Gloves', 24.99, 10, 'boxing-gloves.png'),
('City Bike', 299.99, 10, 'city-bike.png'),
('Surfboard', 399.99, 10, 'surfboard.png')